# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elibrary
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false

#JWT configuration
jwt:
  secret: 'wHS;%@Liz+A/.4f]GsWM4?jMs;crRmK7iGif>}I!dbSfH3g<hJSFt)_tB:il.zd'