# MySQL Configuration
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/elibrary
        username: root
        password: root123
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect